<<<<<<< HEAD
/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
=======
/// <reference types="nativewind/types" />
>>>>>>> 663af87f49b6c2063bb6ee3bd31fe3f2cfba9260
